allowBuilds:
  cpu-features: true
  eslint-plugin-n8n-nodes-base: true
  isolated-vm: true
  ssh2: true
  unrs-resolver: true

overrides:
  'axios@>=1.0.0 <1.18.0': ^1.18.0
  'brace-expansion@<1.1.18': ^1.1.18
  'brace-expansion@>=2.0.0 <2.1.4': ^2.1.4
  'brace-expansion@>=5.0.0 <5.0.9': ^5.0.9
  'form-data@>=4.0.0 <4.0.6': ^4.0.6
  'ip-address@<=10.3.0': ^10.3.1
  'js-yaml@>=4.0.0 <4.3.1': ^4.3.1
  'lodash@>=4.0.0 <=4.17.23': ^4.17.24
  'minimatch@>=9.0.0 <9.0.7': ^9.0.7
  'nanoid@>=3.0.0 <3.3.17': 3.3.17
  'undici@>=6.0.0 <6.28.0': ^6.28.0
